executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: input
    description: Input audio file to be separated into vocals and non-vocals
    json_schema:
      type: string
      ui:widget: file
  - handle: outputDir
    description: Output directory to save the separated vocal files
    json_schema:
      type: string
      ui:widget: save
  - handle: outputBaseName
    description: Base name for output files (optional, uses input filename if not specified)
    json_schema:
      type: string
    nullable: true
    value:
outputs_def:
  - handle: vocals
    description: Separated vocals track file
    json_schema:
      type: string
      ui:widget: file
    nullable: false
  - handle: no_vocals
    description: Separated instrumental track file (no vocals)
    json_schema:
      type: string
      ui:widget: file
    nullable: false
title: Split by vocal
icon: ":twemoji:musical-notes:"
description: |-
  Separates audio into vocals and instrumental tracks (non-vocals).
  outputDir: Directory to save the separated vocal files
  outputBaseName: Base name for output files (optional, uses input filename if not specified)
ui:
  default_width: 487.453125
