executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: audio_file
    description: "%input-audio-file-to-be-separated-into-vocals-and-non-vocals2%"
    json_schema:
      type: string
      ui:widget: file
  - handle: output_dir
    description: "%output-directory-location-to-save-the-separated-vocal-files2%"
    json_schema:
      type: string
      ui:widget: dir
    value: null
    nullable: true
  - handle: output_base_name
    description: "%output-base-name-custom-name-for-output-files-optional-defaults4%"
    json_schema:
      type: string
    value: null
    nullable: true
outputs_def:
  - handle: vocals
    description: "Output: separated vocals track file"
    json_schema:
      type: string
      ui:widget: file
    nullable: false
  - handle: no_vocals
    description: "Output: separated instrumental track file (no vocals)"
    json_schema:
      type: string
      ui:widget: file
    nullable: false
title: "%split-by-vocal2%"
icon: ":twemoji:musical-notes:"
description: "%this-block-separates-audio-files-into-vocals-and-instrumental-tr%"
ui:
  default_width: 487.453125
